### ISSUE TITLE
support for resource expansion

### ISSUE THREAD

**Issue by pgruenbacher** [goadesign/gorma#117]
I couldn't find it in the documentation but having support for resource expansion is the biggest feature I'd be looking for. https://stormpath.com/blog/linking-and-resource-expansion-rest-api-tips

**Comment by raphael** [comment]
That's exactly what views and links in media types are for. There idea is that you list all the "expandable" attributes in the media type then define links for theses attributes. You can then pick and choose which views renders links and which ones render the attributes.

**Comment by pgruenbacher** [comment]
ah well that was really the only thing holding me back. I'll spend some time on it then!
