### ISSUE TITLE
Add missing Resource Payload conversion helpers

### ISSUE THREAD

**Issue by moorereason** [goadesign/gorma#46]
After the major DSL refactor, we lost the resource payload conversion helper functions.  See an example of the old code generation [here](https://github.com/gopheracademy/congo/blob/a1bfdef4b623c8aa4023af976573dcc7ee0562aa/models/proposal/proposal_gen.go#L156-L176).

The old resource template is [here](https://github.com/goadesign/gorma/blob/72235b25ae6dafbde99bb9675332416e88209890/resource_template.go).

**Comment by bketelsen** [comment]
fixed in master
